api_base = "http://127.0.0.1:8000"
SECRET_KEY="place your key here"
SMTP_HOST="smtp.gmail.com"
SMTP_PORT=587
SMTP_USER="yourmail@gmail.com"
SMTP_PASSWORD="place your pass here"
REDIS_URL="redis://localhost:6379/0"
GEMINI_API_KEY="place your key here"
BASE_URL="http://127.0.0.1:8000"  
